### PR TITLE
jest.config: convert to typescript

### PR DESCRIPTION
**Pull request by Mersho**

### CODE REVIEW

**Comment by knocte** [comment]
Why did you propose a PR if CI is still broken?

**Comment by Mersho** [comment]
This Pull Request will be closed due to the TypeScript file being compiled by tsc, which results in the creation of an additional JavaScript file. This leads to an error when running yarn jest due to the presence of multiple configurations.

**Comment by knocte** [comment]
> This leads to an error when running yarn jest due to the presence of multiple configurations.

Cannot you specify which config to use when running the tests?

**Comment by Mersho** [comment]
> > This leads to an error when running yarn jest due to the presence of multiple configurations.
> 
> Cannot you specify which config to use when running the tests?

Yes i can.

**Comment by knocte** [comment]
Then the problem "This leads to an error when running yarn jest due to the presence of multiple configurations." is solved.

**Comment by knocte** [comment]
@Mersho do you understand what my last comment means???

**Comment by Mersho** [comment]
> @Mersho do you understand what my last comment means???

Yes, I'm going to create another PR because i cannot reopen this PR.

**Pull request closed without merging**
