### PR TITLE
Fix truncated body issue

### PR DESCRIPTION
**Pull request by realmarv**

### CODE REVIEW

**Comment by knocte** [comment]
> remove logs

In the same way we're strict about paragraphs beginning with a capital letter, a capital letter needs to be written in a title without area. Please fix this (in this case, it's actually better to rather add an area instead of capitalizing the first 'r'), and create a new rule that detects this.

**Comment by realmarv** [comment]
> > remove logs
> 
> In the same way we're strict about paragraphs beginning with a capital letter, a capital letter needs to be written in a title without area. Please fix this (in this case, it's actually better to rather add an area instead of capitalizing the first 'r'), and create a new rule that detects this.

Done and create a PR for new rule here: https://github.com/nblockchain/conventions/pull/37

**Comment by knocte** [comment]
Can you rebase this PR please? (pushing each commit 1 by 1)

**Comment by realmarv** [comment]
> Can you rebase this PR please? (pushing each commit 1 by 1)

Done

**Comment by knocte** [comment]
@realmarv I examined the CI status of your commits after you have rebased and pushed1by1, and the very first commit says "one failing test", however, CI is not red for it. Please investigate.

**Comment by realmarv** [comment]
This PR is closed and replaced with https://github.com/nblockchain/conventions/pull/38 and https://github.com/nblockchain/conventions/pull/39 because it fixes two bugs in two different rules and we wanted to separate their test cases and fixes.

**Pull request closed without merging**
