### PR TITLE
commitlint: use RuleConfigSeverity enum

### PR DESCRIPTION
**Pull request by realmarv**

### CODE REVIEW

**Comment by knocte** [comment]
Nit: when a PR has 1 single commit, the ideal thing is that its commit message title is same as PR title, and commit message body is same as PR description; because there's no reason for them to differ.

**Comment by realmarv** [comment]
> Nit: when a PR has 1 single commit, the ideal thing is that its commit message title is same as PR title, and commit message body is same as PR description; because there's no reason for them to differ.

Ok, thanks for the note.

**Comment by knocte** [comment]
After I merged the Prettier PR, there are conflicts here, sorry. Can you rebase it? Thanks

**Comment by realmarv** [comment]
> After I merged the Prettier PR, there are conflicts here, sorry. Can you rebase it? Thanks

Done

**Comment by knocte** [comment]
Arghh, this needs a rebase again, sorry.

**Pull request merged**
