### PR TITLE
FileConventions: fix wrapLatestCommitMsg on Win OS

### PR DESCRIPTION
**Pull request by knocte**
Fixes https://github.com/nblockchain/conventions/issues/123

### CODE REVIEW

**Comment by Mersho** [comment]
@knocte I tried it, but nothing changed.

**Comment by knocte** [comment]
Please try again, I overlooked something.

**Comment by Mersho** [comment]
> Please try again, I overlooked something.

script is working now. 👍

**Comment by Mersho** [comment]
During the test, i found a bug:

Steps to reproduce:
1. 
```
git commit -m "foo: testing
>
> This is a so long long long long long long long long long long long long long long long long long commmit" --allow-empty
```

2. ```dotnet fsi .\scripts\wrapLatestCommitMsg.fsx```

**Comment by knocte** [comment]
Your info is terribly confusing; first you say it works and later you report a bug? are you saying it works generally but not for this specific case? FFS please try to think of what people might think when reading your messages.

**Comment by Mersho** [comment]
> Your info is terribly confusing; first you say it works and later you report a bug? are you saying it works generally but not for this specific case? FFS please try to think of what people might think when reading your messages.

it works. but the bug I reported occurs when a commit is empty.

**Comment by knocte** [comment]
That's more clear, please open a bug about that.

**Pull request merged**
