### PR TITLE
Use Error status for body leading black rule

### PR DESCRIPTION
**Pull request by realmarv**
Replaced https://github.com/nblockchain/conventions/pull/11

### CODE REVIEW

**Comment by knocte** [comment]
You didn't push 1by1.

**Comment by realmarv** [comment]
> You didn't push 1by1.

Fixed it

**Comment by knocte** [comment]
You forgot to remove the TODO item that PR removes and to link each PR with each other.

**Comment by knocte** [comment]
And it needs a rebase again :sob:

**Comment by realmarv** [comment]
> You forgot to remove the TODO item that PR removes and to link each PR with each other.

Done

**Comment by knocte** [comment]
> plugins.test: add failing test

`plugins.test` is not an area, it's a sub-area. Zahra remember this repo is called `conventions`, it has more things than commitlint.

**Comment by knocte** [comment]
CI is red.

**Comment by realmarv** [comment]
> > plugins.test: add failing test
> 
> `plugins.test` is not an area, it's a sub-area. Zahra remember this repo is called `conventions`, it has more things than commitlint.

Right. Fixed it.

**Pull request merged**
