### PR TITLE
commitlint,docs: start using FP patterns

### PR DESCRIPTION
**Pull request by knocte**

### CODE REVIEW

**Comment by knocte** [comment]
@webwarrior-ws hey Taras can you investigate why the 2nd commit of this PR breaks tests please? I'm very confused.

**Comment by webwarrior-ws** [comment]
You've used class `None` instead of its instance, and that lead to `instanceof None` check to always fail.
I've added commit to fix it: https://github.com/webwarrior-ws/conventions/commits/wip/fp/

**Comment by knocte** [comment]
Thanks

**Comment by webwarrior-ws** [comment]
There was a bug in `IsInstanceOf`, I fixed it - see last commit in https://github.com/webwarrior-ws/conventions/commits/wip/fp/
CI is red because of formatting in other files.

**Pull request merged**
