### PR TITLE
.gitignore: add .nuget

### PR DESCRIPTION
**Pull request by Mersho**

### CODE REVIEW

**Comment by knocte** [comment]
@Mersho please rebase

**Comment by knocte** [comment]
WHENEVER YOU REBASE SOMETHING, IF THE COMMIT CHANGES THEN YOU HAVE TO SEE, LOOK AROUND TO CHECK IF YOU NEED TO UPDATE THINGS! SEE THE PR TITLE PLEASE

**Comment by knocte** [comment]
You said in telegram "I think this PR is useless now". THIS GIVES ME SO MUCH CONFUSION! FOR SO MANY REASONS:
1. WHY ARE YOU RAISING IT IN TELEGRAM INSTEAD OF HERE??? Remember the handbook says to USE THE RIGHT TOOL FOR THE RIGHT JOB. IF YOU ARE NOT ASKING ME A QUESTION ABOUT IT THAT REQUIRES DISCUSSION, THEN THERE IS NO POINT IN RAISING IT IN TELEGRAM!
2. THIS PR USED TO ADD 2 THINGS TO GITIGNORE, NOW AFTER BEING REBASED IT ONLY ADDS ONE. WHY THIS ONE IS USELESS AND THE OTHER ONE WAS NOT?
3. IF IT IS USELESS, WHY WAS IT BEING INCLUDED IN THE FIRST PLACE???????
4. THE COMMIT MESSAGE IS SAYING THE WHAT, AND NOT THE WHY!!! I DONT KNOW HOW MANY TIMES I HAVE TO STRESS THIS

**Comment by Mersho** [comment]
> 2\. WHY THIS ONE IS USELESS AND THE OTHER ONE WAS NOT?
> 3\. IF IT IS USELESS, WHY WAS IT BEING INCLUDED IN THE FIRST PLACE

I only include items in .gitignore that are common across .NET repositories. Since I didn't observe any .nuget directory in my local environment, I think it might not be necessary to add it.

**Comment by knocte** [comment]
THEN WHY DID YOU OPEN THIS PR IN THE FIRST PLACE???????????

**Comment by Mersho** [comment]
> THEN WHY DID YOU OPEN THIS PR IN THE FIRST PLACE???????????

Okay, I'm going to close this PR.

**Comment by knocte** [comment]
You didn't answer my question. WHEN I ASK SOMETHING IT IS BECAUSE I WANT AN ANSWER, NOT THAT I WANT AN ACTION DONE

**Comment by Mersho** [comment]
> THEN WHY DID YOU OPEN THIS PR IN THE FIRST PLACE???????????

Because 8 month ago this repo doesn't have `packages/` in .gitignore

image

**Comment by knocte** [comment]
YOU KNOW THAT I'M NOT ASKING THAT QUESTION! WE ARE TALKING ABOUT .nuget HERE!!!!!!!!!!!!!!

**Comment by Mersho** [comment]
The .nuget directory is used to manage package dependencies for .NET projects.

Since we use `globalPackagesFolder` in `packages.config` and we specified the packages directory so i think we don't have to put .nuget in .gitignore.

**Comment by knocte** [comment]
> The .nuget directory is used to manage package dependencies for .NET projects.

You are wrong, where did you get this info?

AND YOU STILL DIDN'T ANSWER MY QUESTION! I AM ASKING WHY DID YOU PROPOSE THIS CHANGE AT THE BEGINNING, AND YOU ARE TRYING TO FIND REASONS NOW! TELL ME THE REASONS YOU HAD BEFORE!

**Comment by knocte** [comment]
Your lack of answer makes me think that we're in a similar case to this:

https://twitter.com/deliprao/status/1753141214415667565

(Except: in Linus' sentence, just replace the word "function" with ".nuget string" and "code" with "PR"; and then same point applies.)

**Pull request closed without merging**
