### PR TITLE
Fix truncated body issue

### PR DESCRIPTION
**Pull request by realmarv**

### CODE REVIEW

**Comment by knocte** [comment]
Why does the test not have an empty 2nd line? we don't want a test to fail for the wrong reason.

**Comment by realmarv** [comment]
> Why does the test not have an empty 2nd line? we don't want a test to fail for the wrong reason.

Sorry fixed it

**Comment by knocte** [comment]
Why are you using backticks for the message in the test instead of double-quotes like other tests?

**Comment by knocte** [comment]
Please squash the last commit in the proper place.

**Comment by knocte** [comment]
> Sorry fixed it

@realmarv you fixed it in this PR but not in the commitlint bug.

**Comment by realmarv** [comment]
> > Sorry fixed it
> 
> @realmarv you fixed it in this PR but not in the commitlint bug.

Done

**Pull request merged**
