### PR TITLE
GitHubCi: improved not using GitPush1by1 message

### PR DESCRIPTION
**Pull request by kubaflo**

### CODE REVIEW

**Comment by knocte** [comment]
@realmarv why is CI of this PR red? please investigate

**Comment by knocte** [comment]
@kubaflo can you rebase this PR please.

**Comment by knocte** [comment]
@kubaflo please fix CI

**Comment by realmarv** [comment]
@kubaflo It is not necessary for every commit to pass the CI since some commits intentionally include failing tests as part of the Test-Driven Development (TDD) approach, which is perfectly acceptable.

**Comment by kubaflo** [comment]
@realmarv @knocte I don't really understand what you want from my side :/ I just added 8 words to the message for users

**Comment by knocte** [comment]
Zahra is saying that if a particular commit is adding a failing test, then it is not required that the CI is green. So your message  saying "to make sure every commit passes the CI" could be misleading. Don't you understand? Then what you have to say is to have a CI status, not to pass CI.

**Comment by kubaflo** [comment]
> Zahra is saying that if a particular commit is adding a failing test, then it is not required that the CI is green. So your message saying "to make sure every commit passes the CI" could be misleading. Don't you understand? Then what you have to say is to have a CI status, not to pass CI.

@knocte aaa Okay that makes sense now. Thanks for clarifying

**Pull request merged**
